# Generated by Django 4.1.7 on 2023-03-27 13:04

from django.db import migrations


def create_feelings(apps, schema_editor):
    Feeling = apps.get_model("nvc", "Feeling")
    FeelingsGroup = apps.get_model("nvc", "FeelingGroup")

    happy_group = FeelingsGroup.objects.create(name="happy")
    happy_feelings = [
        "Happy",
        "Joyful"
    ]
    for feeling in happy_feelings:
        Feeling.objects.create(
            name=feeling,
            when_needs_met=True,
            when_needs_not_met=False,
            group=happy_group,
        )

    grateful_group = FeelingsGroup.objects.create(name="grateful")
    grateful_feelings = ["Grateful", "Appreciative", "Touched", "Expansive"]
    for feeling in grateful_feelings:
        Feeling.objects.create(
            name=feeling,
            when_needs_met=True,
            when_needs_not_met=False,
            group=grateful_group,
        )

    eager_group = FeelingsGroup.objects.create(name="eager")
    eager_feelings = [
        "Eager",
        "Excited",
        "Thrilled"
    ]
    for feeling in eager_feelings:
        Feeling.objects.create(
            name=feeling,
            when_needs_met=True,
            when_needs_not_met=False,
            group=eager_group,
        )

    pleased_group = FeelingsGroup.objects.create(name="pleased")
    pleased_feelings = [
        "Pleased", 
        "Content", 
        "Satisfied", 
        "Fulfilled"
    ]
    for feeling in pleased_feelings:
        Feeling.objects.create(
            name=feeling,
            when_needs_met=True,
            when_needs_not_met=False,
            group=pleased_group,
        )

    curious_group = FeelingsGroup.objects.create(name="curious")
    curious_feelings = [
        "Curious", 
        "Interested", 
        "Absorbed"
    ]
    for feeling in curious_feelings:
        Feeling.objects.create(
            name=feeling,
            when_needs_met=True,
            when_needs_not_met=False,
            group=curious_group,
        )

    relieved_group = FeelingsGroup.objects.create(name="relieved")
    relieved_feelings = [
        "Relieved", 
        "At ease", 
        "Rested",
        "Relaxed"
    ]
    for feeling in relieved_feelings:
        Feeling.objects.create(
            name=feeling,
            when_needs_met=True,
            when_needs_not_met=False,
            group=relieved_group,
        )

    affectionate_group = FeelingsGroup.objects.create(name="affectionate")
    affectionate_feelings = [
        "Friendly", 
        "Affectionate", 
        "Loving",
        "Passionate"
    ]
    for feeling in affectionate_feelings:
        Feeling.objects.create(
            name=feeling,
            when_needs_met=True,
            when_needs_not_met=False,
            group=affectionate_group,
        )



class Migration(migrations.Migration):
    dependencies = [
        ("nvc", "0003_feelinggroup_feeling_group"),
    ]

    operations = [migrations.RunPython(create_feelings)]
